// <auto-generated />
using System;
using HolisticAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HolisticAI.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330021736_AddPasswordResetFlow")]
    partial class AddPasswordResetFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HolisticAI.API.Models.CadastroPacienteDetalhado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioTratamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FamiliaOrigem")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoPrincipal")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profissao")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Religiao")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RotinaAtual")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SaudeMedicacao")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeioAtravesDe")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("CadastrosDetalhados");
                });

            modelBuilder.Entity("HolisticAI.API.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terapia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaVisita")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("HolisticAI.API.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UtilizadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("HolisticAI.API.Models.ProfessionalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AceitouTermosEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistroProfissional")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfessionalProfiles");
                });

            modelBuilder.Entity("HolisticAI.API.Models.ProntuarioRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraBase")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraCardiaco")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraCoronario")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraFrontal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraLaringeo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraPlexo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChakraSacral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConteudoFinal")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConteudoGeradoIa")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPorNome")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("CriadoPorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Espiritualidade")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Familia")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GeradoPorIa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeloIa")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesSessao")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrientacaoParaCasa")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prosperidade")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelacoesAfetivas")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatoInicial")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoEnergetica")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerapiaAplicada")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trabalho")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TratamentoExecutado")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("HolisticAI.API.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terapia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("HolisticAI.API.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("HolisticAI.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HolisticAI.API.Models.CadastroPacienteDetalhado", b =>
                {
                    b.HasOne("HolisticAI.API.Models.Paciente", "Paciente")
                        .WithOne("CadastroDetalhado")
                        .HasForeignKey("HolisticAI.API.Models.CadastroPacienteDetalhado", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HolisticAI.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("HolisticAI.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HolisticAI.API.Models.ProfessionalProfile", b =>
                {
                    b.HasOne("HolisticAI.API.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("HolisticAI.API.Models.ProfessionalProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HolisticAI.API.Models.ProntuarioRegistro", b =>
                {
                    b.HasOne("HolisticAI.API.Models.Paciente", "Paciente")
                        .WithMany("Prontuarios")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HolisticAI.API.Models.Sessao", b =>
                {
                    b.HasOne("HolisticAI.API.Models.Paciente", "Paciente")
                        .WithMany("Sessoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HolisticAI.API.Models.User", b =>
                {
                    b.HasOne("HolisticAI.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HolisticAI.API.Models.Paciente", b =>
                {
                    b.Navigation("CadastroDetalhado");

                    b.Navigation("Prontuarios");

                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
